version: "3.9"
services:

  backend:
    build: apps/.
    image: zeffry/simple-apps
    restart: always
    environtment:
     - DB_NAME=training 
     - DB_HOST=localhost 
     - DB_USER=peserta
     - DB_PASS=password 
     - APP_PORT=3000
    links:
      - db
    ports:
      - "3000"
    volumes:
      - app-data:/app/public/images

  db:
    image: "mariadb"
    restart: always
    links:
      - phpmyadmin
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=training
      - MYSQL_USER=peserta
      - MYSQL_PASSWORD=password
    volumes:
      - ./apps/database/:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: "phpmyadmin"
    restart: always
    ports:
      - "9080:80"
    environment:
      - PMA_HOST=db

  web:
    build: ./nginx
    restart: always
    ports:
    - "80:80"
    depends_on:
    - backend

volumes:
  app-data:
  db-data: